export class franchis {
constructor(
  public id?: number,
  public  isActive?:boolean,
  public createdOn?:string,
  public   createdBy?: string,
  public  updatedOn?:string ,
  public   updatedBy?: string,
  public   userName?:string ,
  public   password?:string ,
  public   email?:string ,
  public  businessName?:string,
  public   foodLincNum?:string ,
  public  gst?:string ,
  public  cityId?: number,
  public  city?:string ,
  public stateId?: number,
  public state?:string,
  public   pinCode?:string ,
  public   isFranchise?: number,
  public   parentCompanyId?: number,
  public  address?:string,
  public  franchiseAdminId?: number,
  public   result?:string,
  public   contact?:number,
  public  name?:string,
){}

}
export interface captain{
    id?:number,
    isActive?:boolean,
    createdOn?:number,
    createdBy?:number,
    updatedOn?:number,
    updatedBy?:number,
    result?:string,
    user?:{
      id?:number,
      isActive?:boolean,
      createdOn?:string,
      createdBy?:number,
      updatedOn?:string,
      updatedBy?:number,
      name?:string,
      userType?: number,
      userName?:string,
      email?:string,
      contact?:string,
      password?:string,
      address?:string,
      cityId?:number,
      stateId?:number,
      city?:string,
      state?:string,
      pinCode?:string,
      resetPasswordLink?:string,
      isEmailVerified?:string,
      isFranchiseAdmin?:number,
      iscaptain?:number
    },
    tableList?: [
      {
        id?:number,
        isActive?:boolean,
        createdOn?: string,
        createdBy?:number,
        updatedOn?:string,
        updatedBy?:string,
        name?:string,
        seat?:number,
        isAc?:boolean,
        shape?: string,
        barcodeTest?: string,
        isBooked?: boolean,
        captainId?: number
      }
    ]
}